# -*- coding: utf-8 -*-
"""HABBAS_PlusOCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-0Pw5bK7WgQkkI3Z0AVwospW9olijTwC
"""

import tensorflow as tf
from tensorflow.keras import *
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow_datasets as tfds

# from google.colab import drive
# drive.mount("/content/drive",force_remount=True)

# tesseract imagename outputbase

!sudo apt install tesseract-ocr
!pip install pytesseract

# import libraries
import pytesseract
import shutil
import os
import random
try:
 from PIL import Image
except ImportError:
 import Image

# Upload Image 
from google.colab import files
uploaded = files.upload()

# Text Extraction 
!pip install --ignore-installed Pillow==9.0.0

image_path_in_colab = "improved-results-leave-one-dataset-out.png"
extractedInformation = pytesseract.image_to_string(Image.open(image_path_in_colab))
print(extractedInformation)

# Get Bounding Boxes for Text
# Get bounding box estimates
print(pytesseract.image_to_boxes(Image.open(image_path_in_colab)))